name: Parallel test run

on:
  schedule:
    - cron: "00 02 * * *"
  workflow_dispatch: { }
  pull_request:
    branches: [ "master" ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ "master" ]
env:
  ENVIRONMENT: Stage
permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22
      - name: Build with Maven
        run: mvn -B validate --file pom.xml

  test_run:
    needs: build
    runs-on: ubuntu-latest
    steps:
#      - uses: browser-actions/setup-chrome@latest
#        with:
#          chrome-version: stable
      - uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Test with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/suites/testng_parallel.xml

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/surefire-reports
          allure_history: allure-history

      - name: Logs uploading
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/logs

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          cname: kandrusik.github.io/parallel-automation
